# Generated by Django 4.2.2 on 2023-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.BooleanField(default=True)),
                ('dateCheckedIn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkOutText', models.TextField(blank=True, max_length=300, null=True)),
                ('check_out', models.BooleanField(default=False)),
                ('dateCheckedOut', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
