# Generated by Django 4.2.2 on 2023-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='dateCheckedIn',
            field=models.DateTimeField(default='Date Checked In'),
        ),
    ]
