# Generated by Django 4.2.2 on 2023-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_alter_check_in_datecheckedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out',
            name='dateCheckedOut',
            field=models.DateTimeField(default='Date Checked In'),
        ),
    ]
