# Generated by Django 4.2 on 2023-07-04 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apply', '0003_alter_check_out_datecheckedout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(max_length=254)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('courses', models.CharField(choices=[('SWeb Development', 'Web Development'), ('App Development', 'App Development'), ('Data Science', 'Data Science'), ('Digital Marketing', 'Digital Marketing'), ('Content Management', 'Content Management'), ('UX/UI Design', 'UX/UI Design'), ('Graphic Design', 'Graphic Design'), ('Mentorship', 'Mentorship')], max_length=100)),
                ('any_programming_skill', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('choose_internship_type', models.CharField(choices=[('secondary', 'Secondary Internship Programs'), ('undergraduate', 'Undergraduate Internship Programs'), ('postgraduate', 'Postgraduate Internship Programs')], max_length=100)),
                ('number_of_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('upload_photo', models.ImageField(upload_to='photos/')),
                ('upload_it_letter', models.FileField(upload_to='it_letters/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
