# Generated by Django 4.2 on 2023-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_contact_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='courses',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Data Science', 'Data Science'), ('Digital Marketing', 'Digital Marketing'), ('Content Management', 'Content Management'), ('UX/UI Design', 'UX/UI Design'), ('Graphic Design', 'Graphic Design'), ('Mentorship', 'Mentorship')], max_length=100),
        ),
    ]
